# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: build application
      run: |
          cd bps
          python bps_compiler_of_book.py -b="bp_compiler_out.out" -m="makefile_bps.json" 
    - name: Create file
      run: |
        printf "Hello\nWorld\n" > hw.txt
    - name: Create file
      run: |
        echo First        > other.txt
        echo Second Line >> other.txt
        echo Third       >> other.txt
    - name: Show file content
      run: |
        pwd
        ls -la
        cat hw.txt
        cat other.txt
    - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'building a bps'
          
